# Generated by Django 4.1.7 on 2023-03-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_user_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=11500)),
                ('api_key', models.CharField(max_length=11500)),
            ],
        ),
    ]
