# Generated by Django 4.1.7 on 2023-04-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_prompt_delete_data_delete_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images')),
                ('email', models.CharField(max_length=400)),
            ],
        ),
    ]
