# Generated by Django 4.1.7 on 2023-04-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_profiledata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('user', models.CharField(max_length=300)),
                ('prompt_title', models.CharField(max_length=300)),
                ('prompt_id', models.CharField(max_length=300)),
                ('chat', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='profiledata',
            name='picture',
            field=models.ImageField(blank=True, default='profile_images/default.png', null=True, upload_to='profile_images'),
        ),
    ]
