# Generated by Django 4.1.7 on 2023-05-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_chat_alter_profiledata_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='Views',
            field=models.CharField(blank=True, default=0, max_length=100000, null=True),
        ),
    ]
