# Generated by Django 4.1.7 on 2023-05-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_prompt_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='savedPrompts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('Description', models.TextField()),
                ('prompt_text', models.TextField()),
                ('Time', models.TimeField(auto_now_add=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('User', models.CharField(max_length=500)),
                ('Views', models.CharField(blank=True, default=0, max_length=100000, null=True)),
                ('saved_by', models.CharField(max_length=1000)),
            ],
        ),
    ]
