# Generated by Django 4.1.7 on 2023-05-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_savedprompts'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='img',
            field=models.ImageField(blank=True, default='profile_images/default.png', null=True, upload_to='Prompts Images'),
        ),
    ]
