# Generated by Django 4.1.7 on 2023-05-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_prompt_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedprompts',
            name='img',
            field=models.ImageField(blank=True, default='profile_images/default.png', null=True, upload_to='savedPrompts Images'),
        ),
    ]
