# Generated by Django 4.1.7 on 2023-05-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_savedprompts_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='user_img',
            field=models.ImageField(blank=True, default='profile_images/default.png', null=True, upload_to='userImages'),
        ),
        migrations.AddField(
            model_name='savedprompts',
            name='user_img',
            field=models.ImageField(blank=True, default='profile_images/default.png', null=True, upload_to='userImages'),
        ),
    ]
