# Generated by Django 4.1.7 on 2023-05-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_savedprompts_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedprompts',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
