# Generated by Django 4.1.7 on 2023-05-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_savedprompts_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedprompts',
            name='pid',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
